spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true